### ISSUE TITLE
Electra changes to AC app

### ISSUE THREAD

**Issue by arnonm** [jafar-atili/pyElectra#13]
Just got a new Electra AC this week. Electra now directs you to a new app "Smart Home by Aideology"
This registers your AC differently.
As a result (I think), the current implementation is not working 1.2.4

**Comment by arnonm** [comment]
Validated that API is working with PostMan, but not working with 1.2.4, either directly with pyElectra or Home Assistant.

**Comment by arnonm** [comment]
Errors from HomeAssistant:
2024-12-19 13:40:00.820 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 0545297311 for electrasmart
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/electrasmart/__init__.py", line 29, in async_setup_entry
    await cast(ElectraAPI, hass.data[DOMAIN][entry.entry_id]).fetch_devices()
  File "/usr/local/lib/python3.13/site-packages/electrasmart/api/__init__.py", line 162, in fetch_devices
    await task
  File "/usr/local/lib/python3.13/site-packages/electrasmart/api/__init__.py", line 189, in get_last_telemtry
    ac.update_operation_states(resp[Attributes.DATA])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/electrasmart/device/__init__.py", line 123, in update_operation_states
    self._oper_data = json.loads(data["commandJson"]["OPER"])["OPER"]
                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                    f'not {s.__class__.__name__}')
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by arnonm** [comment]
My output from GET_DEVICES:
{"id":99,"status":0,"desc":null,"data":{"devices":[{"providerName":"Electra","deviceTypeName":"A/C","manufactor":"מזגן
עילי","photoId":null,"permissions":15,"isGroupMember":false,"mode":null,"temperature":null,"OwnerUsername":"0521234567","deviceTypeId":1,"name":"אווה","status":0,"providerid":1,"latitude":null,"longitude":null,"location":null,"sn":"4M41610861","mac":"B80BDA91A782","model":null,"hwVersion":null,"fmVersion":null,"userId":445080,"manufactorId":2,"iconId":null,"hasImage":false,"deviceToken":"xxxxxxxxx","mqttId":null,"enableEvents":true,"isActivated":false,"logLevel":null,"lastIntervalActivity":null,"powerKWH":null,"hasProblem":false,"IsDebugMode":false,"regdate":"2024-12-18T20:04:14","id":245369}],"res":0,"res_desc":null}}
My output from GET LAST_TELEMETRY:
{"id":99,"status":0,"desc":null,"data":{"timeDelta":200000,"commandJson":{"OPER":null,"DIAG_L2":null},"res":0,"res_desc":null}}

**Comment by nirizr** [comment]
Any progress handling this issue? I'm also having trouble with it!
